// Generated by CoffeeScript 1.6.3
(function() {
  var a1, a2, a3, back_alley_cinema, local_cinema;

  a1 = ['one', 2, "three"];

  a2 = ['two', 3, "four"];

  a3 = ['three', 3, 'four', 4, 'five', 5];

  local_cinema = {
    'blows up cars': ['12:30', '3:30', '7:40'],
    'blows up people': ['11:30', '3:10', '6:20'],
    'end of world': ['10:30', '4:30'],
    'mad face kill bad guys': ['11:35']
  };

  back_alley_cinema = {
    'Calcutta': ['3:10'],
    'Titicut Follies': ['12:35']
  };

}).call(this);
