// Generated by CoffeeScript 1.6.3
(function() {
  var Employee, emp1, emp2;

  Employee = (function() {
    function Employee(name) {
      this.name = name;
      console.log("Instantiated a new Employee object with a name of " + this.name);
    }

    Employee.prototype.dob = function(year, month, day) {
      if (year == null) {
        year = 1981;
      }
      if (month == null) {
        month = 12;
      }
      if (day == null) {
        day = 5;
      }
      return new Date(year, month, day);
    };

    return Employee;

  })();

  emp1 = new Employee('Jen');

  console.log(emp1.dob());

  emp2 = new Employee('Tom');

  console.log(emp2.dob(1957, 6, 2));

}).call(this);
