// Generated by CoffeeScript 1.6.3
(function() {
  var myArray,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  myArray = ['one', 'two', 'three'];

  if (__indexOf.call(myArray, "one") >= 0) {
    console.log("I found one");
  }

  if (__indexOf.call(myArray, "six") < 0) {
    console.log("''six' was nowhere to be found");
  }

}).call(this);
