// Generated by CoffeeScript 1.6.3
(function() {
  var a, key, letter, letters, myLetters, num, person, times, value, _i, _j, _k, _len, _len1, _len2;

  myLetters = ["a", "b", "c", "d"];

  for (_i = 0, _len = myLetters.length; _i < _len; _i++) {
    letter = myLetters[_i];
    console.log(letter.toUpperCase());
  }

  letters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];

  for (_j = 0, _len1 = letters.length; _j < _len1; _j += 2) {
    letter = letters[_j];
    console.log(letter);
  }

  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  for (_k = 0, _len2 = a.length; _k < _len2; _k++) {
    num = a[_k];
    if (num < 5) {
      console.log(num);
    }
  }

  person = {
    firstName: "Tom",
    lastName: "Dyer"
  };

  for (key in person) {
    value = person[key];
    console.log("" + key + " is " + value);
  }

  times = function(number_of_times, callback) {
    var index;
    index = 0;
    while (index++ < number_of_times) {
      callback(index);
    }
    return null;
  };

  times(5, function(index) {
    return console.log(index);
  });

  times = function(number_of_times, callback) {
    var index;
    index = 0;
    while (!(index++ >= number_of_times)) {
      callback(index);
    }
    return null;
  };

  times(5, function(index) {
    return console.log(index);
  });

}).call(this);
