// Generated by CoffeeScript 1.6.3
(function() {
  var myFunc, obj;

  obj = {
    firstName: "Mark",
    lastName: "Bates",
    fullName: function() {
      return "" + this.firstName + " " + this.lastName;
    }
  };

  console.log("firstName: " + obj.firstName + ", lastName: " + obj.lastName + ", fullName: " + (obj.fullName()));

  myFunc = function(options) {
    return console.log(JSON.stringify(options));
  };

  myFunc({
    foo: 'Foo',
    bar: 'Bar'
  });

}).call(this);
