// Generated by CoffeeScript 1.6.3
(function() {
  console.log("foo" === "foo");

  console.log("foo" !== "bar");

  console.log(true === !false);

  console.log("cake" && "eat it");

  console.log("money" || "your life");

  if (false === true) {
    console.log('Huh');
  }

  console.log(false === false);

  console.log(window === this);

  this.foo_bar = 33.8;

}).call(this);
