// Generated by CoffeeScript 1.6.3
(function() {
  var firstThree, largeRange, myArray, myRange, myRangeExclusive, rangeDownTo, _i, _ref, _ref1, _results;

  myRange = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(myRange);

  myRangeExclusive = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log(myRangeExclusive);

  rangeDownTo = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1];

  console.log(rangeDownTo);

  largeRange = (function() {
    _results = [];
    for (_i = 5; _i <= 55; _i++){ _results.push(_i); }
    return _results;
  }).apply(this);

  console.log(largeRange);

  myArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  firstThree = myArray.slice(0, 3);

  console.log(firstThree);

  myArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(myArray);

  [].splice.apply(myArray, [4, 4].concat(_ref = ['a', 'b', 'c', 'd'])), _ref;

  console.log(myArray);

  myArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  console.log(myArray);

  [].splice.apply(myArray, [4, (-1) - 4 + 1].concat(_ref1 = ['a', 'b', 'c', 'd'])), _ref1;

  console.log(myArray);

}).call(this);
