// Generated by CoffeeScript 1.6.3
/*
I'm a block level comment
Cuz I've got a lot 
to 
Say on 
many lines
See how block level comments 
show up in the generated javascript.
*/


(function() {
  var name, person, showBrokenWhitespace, showName, showNameDefault, showSplatName, yell,
    __slice = [].slice;

  person = true;

  name = "Tom";

  /*
  log my name
  */


  console.log(name);

  yell = function() {
    return alert("name is " + name);
  };

  yell();

  showName = function(name) {
    return console.log("my name is " + name);
  };

  showName('Jack');

  showNameDefault = function(name) {
    if (name == null) {
      name = "Joe";
    }
    return console.log("my name is " + name);
  };

  showNameDefault();

  showSplatName = function() {
    var etc, name;
    name = arguments[0], etc = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    console.log(name);
    return console.log(etc);
  };

  showSplatName('Alice', 'Bob', 'Joe', 'Sigmund');

  showBrokenWhitespace = function() {
    return console.log('me not broken here');
  };

}).call(this);
